#
# Automagically generated by Approximatrix Simply Fortran 2.41
#
FC="gfortran"
CC="gcc"
AR="ar"
WRC="windres"
RM=rm -f

IDIR=

LDIR=-L/snap/simplyfortran/4/bin/../lib/ 


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

clean: .SYMBOLIC
	@echo Deleting target
	@$(RM) "target"

"target":  "build/Test1.prj.target"
	@echo Generating target
	@$(FC) -o "target" -static $(LDIR) $(PRJ_LFLAGS)

all: "target" .SYMBOLIC

